### ISSUE TITLE
Suggestion: Change node sorting order

### ISSUE THREAD

**Issue by TheSillyDoggo** [geode-sdk/DevTools#20]
Instead of ordering it in the z order of the node it should be the child index so it's in the same order that it should be.

also you can make it an option but that doesn't have to happen

**Comment by matcool** [comment]
i dont get it

**Comment by TheSillyDoggo** [comment]
Devtools sorts the nodes by it's z order so it has the lowest z up the top
and the highest at the bottom. That makes getting a node by it's index
harder

**Comment by Capeling** [comment]
so just sort them by there index instead of by z order

**Comment by TheSillyDoggo** [comment]
That's what I was saying

**Comment by matcool** [comment]
there is no node index. the order of nodes during an init function is only temporary, as cocos then sorts the nodes by z order the next frame ish, which is what devtools shows. we dont sort the nodes by z order, we just iterate them by what getChildren() return

**Comment by TheSillyDoggo** [comment]
Oh I didn't understand mostly because I only use get children in the init
functions so that's why
