### ISSUE TITLE
Doesn't load on MacOS (platform binary not found)

### ISSUE THREAD

**Issue by 12944qwerty** [geode-sdk/DevTools#28]
I installed the latest release (1.5.0)
![image](https://github.com/geode-sdk/DevTools/assets/45984786/cc946ca9-02ae-4334-8afa-0d8586e7f76a)

**Comment by coopeeo** [comment]
The DevTools Mod doesn't support the macOS platform (yet).
Also on the bottom line it says that its not supported on this platform.

**Comment by 12944qwerty** [comment]
Yeah, i know that, but it seemed like it had been supported everywhere else. On the README it says F10 for mac for example so that just led me to believe it was supported on mac.

**Comment by MarioMastr** [comment]
sounds like the readme just needs to be updated to say mac unsupported
